### ISSUE TITLE
Unknown Plugins Scope 'schema'

### ISSUE THREAD

**Issue by codewith-luke** [moonrepo/proto#164]
Just installed proto and trying to install Moon Repo using it. 

```toml
[plugins]
moon = "schema:https://raw.githubusercontent.com/moonrepo/moon/master/proto-plugin.toml"
```

When then running `proto install moon` we see:

```
Error: proto::misc

  × Unknown plugin scope `schema`.
```
