### ISSUE TITLE
Add support for zig

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/proto#237]
### What happened?

Would be great if zig supported is added at https://moonrepo.dev/docs/proto/tools.

I'm primarily looking to use [cargo-zigbuild](https://github.com/rust-cross/cargo-zigbuild/tree/main) to create cross platform binaries from the same machine.

### Operating system?

Linux

### Architecture?

x64

**Comment by prabirshrestha** [comment]
Is it possible for this to be local path instead of `https://`. I would like to check it in my repro.

```toml
[plugins]
my-tool = "source:https://raw.githubusercontent.com/my/tool/master/proto-plugin.toml"
```

It might conflict with `.wasm` files but I think you can easily check the extension or reading few bytes to detect wasm.
