### ISSUE TITLE
Feature request: Plugin checksums

### ISSUE THREAD

**Issue by Phault** [moonrepo/proto#432]
Both wasm and toml plugins should support verifying the downloaded plugins using checksums. Right now a supply chain attack can only be mitigated for TOML plugins under specific circumstance, using the same method as described in #431.

WASM plugins, while pin-able to specific versions, can still have the assets for existing releases swapped to a malicious ones at any point.

For TOML plugins this is not solvable in a clean way before #431 is solved, however it would be possible to prompt the user to approve when the checksum changed, rather than outright rejecting it. But it wouldn't be a usable solution in CI pipelines.

I have a few ideas on how to solve it:

### 1) Add checksum as optional parameter to locators

`^` used as separator here, but could be anything that isn't part of the URI spec. `:` would've been ideal, but it conflicts with urls in `source:`.

```
github:Phault/proto-dotnet-plugin@0.2.2^4b803d939a4767c38f7706506040433a6457bc64b457dfabce01678f33be0354
source:https://wherever.com/plugin.wasm^4b803d939a4767c38f7706506040433a6457bc64b457dfabce01678f33be0354
```

Pros: Not a big change, only 1 line that changes when a plugin is updated.
Cons: It's long and ugly.

### 2) Add separate `[checksums]` section to  .prototools

```toml
dotnet = "8.0.201"

[plugins]
dotnet = "github:Phault/proto-dotnet-plugin@0.2.2"

[checksums]
dotnet = "4b803d939a4767c38f7706506040433a6457bc64b457dfabce01678f33be0354"
```

Pros: Simple, clean and does not mess with the plugin locator in any way.
Cons: Not obvious whether this is a checksum for the plugin or the tool itself. Could be solved with better naming maybe?

### 3) Add a proto.lock file

Essentially the same as 2) but moved into its own file, similar to most package managers.

Perhaps controversial due to more clutter and feels overkill for the small amount of plugins are likely to use. If however the plan is to ever have dependency-resolving for plugins, then it could make sense. 

```toml
[dotnet]
sha256 = "4b803d939a4767c38f7706506040433a6457bc64b457dfabce01678f33be0354"
# extra data?
```

---

In any case using `proto plugin add` should be the recommended way to add plugins, so that checksums can be automatically added if missing. Additionally `proto use` could add missing checksums, but that also requires keeping track of which `.prototools` the `plugins` entry came from.

Personally prefer 2. and like 3. the least.
