### ISSUE TITLE
invalid leading zero in patch version number

### ISSUE THREAD

**Issue by W1M0R** [moonrepo/proto#585]
### What version?

0.39.7

### Which command?

proto install

### What happened?

Trying to install pandoc using proto results in the following error:

```pwsh
Error: plugin::call_func::failed

  × invalid leading zero in patch version number
```

This is the release of Pandoc that I'm trying to install: https://github.com/jgm/pandoc/releases/tag/3.3

This is the `.prototools` (redacted):

```toml
pandoc = "3.3"

[plugins]
pandoc = "file://etc/proto/pandoc/plugin.toml"
```

This is the pandoc plugin.toml (work in progress, but can't proceed with testing it until the version issue is resolved):

```toml
name = "pandoc"
type = "cli"

[resolve]
git-url = "https://github.com/jgm/pandoc"

[platform.linux]
download-file = "pandoc-{version}-linux-{arch}.tar.gz"

[platform.macos]
download-file = "pandoc-{version}-{arch}-macOS.zip"

[platform.windows]
download-file = "pandoc-{version}-windows-{arch}.zip"

[install]
download-url = "https://github.com/jgm/pandoc/releases/download/{version}/{download_file}"
```

### Trace logs?

Quite verbose, but can provide it if the issue is not clear.

### Operating system?

Windows

### Architecture?

x64
