### ISSUE TITLE
Feature request: allow http url as https proxy

### ISSUE THREAD

**Issue by AiHMin** [moonrepo/proto#594]
### What version?

0.39.0

### Which command?

proto install

### What happened?

Proto now uses the prefixes `http:` and `https:` to distinguish between an HTTP proxy and an HTTPS proxy. Is it possible to specify an HTTP address (e.g. `http://127.0.0.1:xxx`) for an HTTPS proxy? 

This is particularly useful when the proxy address is set to `127.0.0.1`.

### Operating system?

MacOS

### Architecture?

arm64

**Comment by milesj** [comment]
This is tricky, because not all `127.0.0.1` local URLs are https, most of them are http, so how is proto supposed to know the difference?

**Comment by AiHMin** [comment]
Is it possible to let the configuration file tell proto which are http and which are https?
e.g.:
``` toml
[settings.http]
http-proxies = ["http://127.0.0.1:1234", "http://proxy-url"]
https-proxies = ["http://127.0.0.1:1234", "https://proxy-url"]
```
or 

``` toml
[settings.http]
proxies = ["http://127.0.0.1:1234", "http://proxy-url"]

[settings.https]
proxies = ["http://127.0.0.1:1234", "https://proxy-url"]
```
