### ISSUE TITLE
proto install for github tool tagged not using semantic version (toml plugin)

### ISSUE THREAD

**Issue by shanipribadi** [moonrepo/proto#624]
### What version?

0.41.3

### Which command?

proto install kondo

### What happened?

I'm using the following toml plugin definition (explicit versions instead of resolve.git-url due to the project not creating a tag for releases)

```toml
name = "kondo"
type = "cli"

[resolve]
versions = ["0.8"]

[platform.linux]
archive-prefix = "kondo-{arch}-unknown-linux-{libc}"
download-file = "kondo-{arch}-unknown-linux-{libc}.tar.gz"
checksum-file = "kondo-{arch}-unknown-linux-{libc}.tar.gz.sha256"

[platform.macos]
archive-prefix = "kondo-{arch}-apple-darwin"
download-file = "kondo-{arch}-apple-darwin.tar.gz"
checksum-file = "kondo-{arch}-apple-darwin.tar.gz.sha256"

[platform.windows]
archive-prefix = "kondo-{arch}-pc-windows-msvc"
download-file = "kondo-{arch}-pc-windows-msvc.zip"
checksum-file = "kondo-{arch}-pc-windows-msvc.zip.sha256"

[install]
download-url = "https://github.com/tbillington/kondo/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "i686
```

Getting
```bash
❯ proto install kondo
Error: plugin::call_func::failed

  × Unknown version format `0.8`. Must be a semantic or calendar based format. at line 1 column 107
```

Although the crate in https://github.com/tbillington/kondo actually follows semantic version (they tagged the crate as 0.8.0), but the github releases are not tagged as such.

Would this be a scenario that proto toml plugin should be able to handle,
or should we actually ask upstream to tag their releases with semantic version instead?

### Operating system?

Linux

### Architecture?

x64
