### ISSUE TITLE
npm `shared-globals-dir = true` is not working unless manually create `$PROTO_HOME/tools/node/globals/bin` directory

### ISSUE THREAD

**Issue by frantic1048** [moonrepo/proto#669]
### What version?

0.43.1

## Configuration

With global proto config `~/.proto/.prototools`

```toml
node = "22.12.0"
npm = "bundled"

[tools.node]
bundled-npm = true

[tools.npm]
shared-globals-dir = true

[settings]
auto-install = true
```

And these directories in `PATH`:

- `~/.proto/shims`
- `~/.proto/bin`
- `~/.proto/tools/node/globals/bin`

## Steps to reproduce

Install a global npm binary: `npm install -g nx`

### Expected

There should be a binary named `nx` under `~/.proto/tools/node/globals/bin` directory

### Actual

No binary in installed into `~/.proto/tools/node/globals/bin`, and `~/.proto/tools/node/globals` does not exist.

### Workaround

Manually create `~/.proto/tools/node/globals` directory before installing global npm binary.

```
mkdir -p ~/.proto/tools/node/globals/bin
npm install -g nx
which nx # <-- it points to ~/.proto/tools/node/globals/bin/nx
```

### Operating system?

MacOS

### Architecture?

arm64
